#!/usr/bin/fish

nohup python -u "/workspaces/mictlan/research/funsearch/ui/main.py" > "/workspaces/mictlan/research/funsearch/ui/stdout.log" 2> "/workspaces/mictlan/research/funsearch/ui/stderr.log" &
